### PR TITLE
Fixing everything

### PR DESCRIPTION
**Pull request by dend**

### CODE REVIEW

**Comment by jhutchings1** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[xml/FrameworksIndex/healthvault-1.65.20615.4-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvault-1.65.20615.4-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvault-1.65.20623.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvault-1.65.20623.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultclient-1.65.20615.4-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultclient-1.65.20615.4-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultclient-1.65.20623.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultclient-1.65.20623.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultweb-1.65.20615.4-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultweb-1.65.20615.4-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultweb-1.65.20623.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultweb-1.65.20623.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client/HealthVaultConnectionFactory.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client/HealthVaultConnectionFactory.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IHealthVaultRestClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IHealthVaultRestClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IPersonClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IPersonClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IThingClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IThingClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IVocabularyClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IVocabularyClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Configuration/HealthVaultConfiguration.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Configuration/HealthVaultConfiguration.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Connection/IHealthVaultConnection.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Connection/IHealthVaultConnection.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Connection/SessionCredential.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Connection/SessionCredential.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/ConversionFailureException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/ConversionFailureException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthHttpException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthHttpException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationNotPossibleException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationNotPossibleException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationRequiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationRequiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordReauthorizationRequiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordReauthorizationRequiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceAccessDeniedException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceAccessDeniedException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceApplicationDuplicateCredentialException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceApplicationDuplicateCredentialException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceAuthenticatedSessionTokenExpiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceAuthenticatedSessionTokenExpiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceCredentialTokenExpiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceCredentialTokenExpiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceEmailNotValidatedException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceEmailNotValidatedException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidApplicationAuthorizationException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidApplicationAuthorizationException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidPersonException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidPersonException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidRecordException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidRecordException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceMailAddressMalformedException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceMailAddressMalformedException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServicePasswordNotStrongException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServicePasswordNotStrongException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceRecordQuotaExceededException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceRecordQuotaExceededException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/IncompatibleVersionException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/IncompatibleVersionException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/InvalidConfigurationException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/InvalidConfigurationException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/SignatureFailureException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/SignatureFailureException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/ThingDeserializationException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/ThingDeserializationException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/ThingSerializationException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/ThingSerializationException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/TypeHandlerAlreadyRegisteredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/TypeHandlerAlreadyRegisteredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.ItemTypes/ApplicationSpecific.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.ItemTypes/ApplicationSpecific.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.ItemTypes/ApproximateTime.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.ItemTypes/ApproximateTime.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.ItemTypes/Blob.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.ItemTypes/Blob.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.ItemTypes/HealthGoal.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.ItemTypes/HealthGoal.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.ItemTypes/LabTestResultDetails.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.ItemTypes/LabTestResultDetails.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Person/PersonInfo.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Person/PersonInfo.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlan.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlan.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanFrequencyTaskCompletionMetricsV2.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanFrequencyTaskCompletionMetricsV2.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanInstance.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanInstance.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanInstanceV2.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanInstanceV2.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanTaskInstance.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanTaskInstance.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanTaskInstanceV2.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanTaskInstanceV2.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanTaskV2.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.RestApi.Generated.Models/ActionPlanTaskV2.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C11%5Cd3a7b26e-e832-dfa2-6527-b27014cc5d28%5CPullRequest%5C201707112027024811-31%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dend** [comment]
@davidkwoods all I need to do is provision a couple of new monikers, and I will make sure to merge this.

**Comment by jhutchings1** [comment]
@dend is this good to merge?

**Comment by dend** [comment]
@jhutchings1 just updated the moniker set. Once it builds, I will merge.

**Comment by jhutchings1** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/dend/healthvault-docs/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvault-1.65.20615.4-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvault-1.65.20615.4-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvault-1.65.20623.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvault-1.65.20623.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvault-1.66.20706.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvault-1.66.20706.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultclient-1.65.20615.4-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultclient-1.65.20615.4-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultclient-1.65.20623.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultclient-1.65.20623.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultclient-1.66.20706.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultclient-1.66.20706.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultweb-1.65.20615.4-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultweb-1.65.20615.4-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultweb-1.65.20623.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultweb-1.65.20623.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/FrameworksIndex/healthvaultweb-1.66.20706.2-preview.xml](https://github.com/dend/healthvault-docs/blob/master/xml/FrameworksIndex/healthvaultweb-1.66.20706.2-preview.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Application/Location.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Application/Location.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client.Exceptions/BrowserAuthException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client.Exceptions/BrowserAuthException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client.Exceptions/ShellAuthException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client.Exceptions/ShellAuthException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client.NetFramework/HealthVaultConnectionFactory.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client.NetFramework/HealthVaultConnectionFactory.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client/HealthVaultConnectionFactory.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client/HealthVaultConnectionFactory.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client/IBrowserAuthBroker.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client/IBrowserAuthBroker.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client/IHealthVaultConnectionFactory.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client/IHealthVaultConnectionFactory.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Client/IHealthVaultSodaConnection.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Client/IHealthVaultSodaConnection.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IHealthVaultRestClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IHealthVaultRestClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IPersonClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IPersonClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IPlatformClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IPlatformClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IThingClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IThingClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Clients/IVocabularyClient.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Clients/IVocabularyClient.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Configuration/HealthVaultConfiguration.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Configuration/HealthVaultConfiguration.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Configuration/HealthVaultConfigurationDefaults.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Configuration/HealthVaultConfigurationDefaults.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Connection/IHealthVaultConnection.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Connection/IHealthVaultConnection.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Connection/SessionCredential.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Connection/SessionCredential.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/ConversionFailureException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/ConversionFailureException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthAuthorizedConnectionRequiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthAuthorizedConnectionRequiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthHttpException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthHttpException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationNotPossibleException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationNotPossibleException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationRequiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordAuthorizationRequiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordNotFoundException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordNotFoundException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthRecordReauthorizationRequiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthRecordReauthorizationRequiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceAccessDeniedException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceAccessDeniedException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceApplicationDuplicateCredentialException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceApplicationDuplicateCredentialException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceAuthenticatedSessionTokenExpiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceAuthenticatedSessionTokenExpiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceCredentialTokenExpiredException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceCredentialTokenExpiredException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceEmailNotValidatedException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceEmailNotValidatedException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidApplicationAuthorizationException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidApplicationAuthorizationException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidPersonException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidPersonException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidRecordException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceInvalidRecordException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceMailAddressMalformedException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceMailAddressMalformedException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServicePasswordNotStrongException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServicePasswordNotStrongException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthServiceRecordQuotaExceededException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthServiceRecordQuotaExceededException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/HealthVaultException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/HealthVaultException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/IncompatibleVersionException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/IncompatibleVersionException.xml) | :white_check_mark:Succeeded | |
[xml/Microsoft.HealthVault.Exceptions/InvalidConfigurationException.xml](https://github.com/dend/healthvault-docs/blob/master/xml/Microsoft.HealthVault.Exceptions/InvalidConfigurationException.xml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C17%5Cd3a7b26e-e832-dfa2-6527-b27014cc5d28%5CPullRequest%5C201707172229496354-31%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
